[package]
name = "MatrixOS"
version = "0.1.0"
edition = "2024"

build = "src/build.rs"

[dependencies]
matrix_bootloader_builder = { path = "matrix_bootloader_builder" }

[build-dependencies]
matrix_bootloader_builder = { path = "matrix_bootloader_builder" }
